  CREATE TABLE bookmarks (
      id id INTEGER primary key generated by default as identity,
      title TEXT NOT NULL,
      description TEXT,
      url TEXT NOT NULL,
      rating TEXT,
  );

  insert into bookmarks (title, url, description, rating)
  values (
      ('reddit', 'www.reddit.com', 'front page of the internet', '9'),
      ('thinkful', 'www.thinkful.com'),
      ('github', 'www.github.com', 'repos galore'),
      ('pluralsight', 'www.pluralsight.com, 'learning is fun', '10'),
      ('starbucks', 'www.starbucks.com'),
      ('disneyjr', 'www.disneyjr.com' 'this is my life now', '8'),
      ('udemy', 'www.udemy.com', 'buy learning stuff', '10'),
      ('amazon', 'www.amazon.com', 'so much stuff', '10'),
      ('apple', 'www.apple.com'),
      ('dentyne ice', 'www.dentyneice.com', 'its gum')
        );
